version: "3.9"
services:
  ws-server:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    restart: always
    networks:
      - ws-network
    ports:
      - "3030:3030"

networks:
  ws-network:
